all:
	@echo "------------------------------------------"
	@echo "No makefile required. Solution in Python"
	@echo "Test files in /tests folder."
	@echo "Documentation in README.md file"
	@echo "My project will look a little wierd since"
	@echo "I wrote a generator.Then just modified the"
	@echo "result to fix the conflicts." 
	@echo "------------------------------------------"
