all:
	@echo "------------------------------------------"
	@echo "No makefile required. Solution in Python"
	@echo "Test Scripts in /tests folder."
	@echo "Documentation in documentation.md file"
	@echo "------------------------------------------"
