all:
	@echo "------------------------------------------"
	@echo "No makefile required. Solution in Python"
	@echo "Test files in /tests folder."
	@echo "Documentation in README.md file"
	@echo "Project 4 - Code Generation"
	@echo "Nagavarun Kanaparthy"
	@echo "------------------------------------------"
